Fix static analysis tools
IntelPython/daal4py pull request #301
Opened 2020-09-24 13:17 UTC by Pahandrovich

2020-09-24 17:03 UTC, napetrov commented
New  code introduce 3 code factor issues - suggest to fix them now . Overall looks good

2020-09-24 21:01 UTC, PetrovKP requested changes

2020-09-24 21:01 UTC, PetrovKP commented on daal4py/sklearn/decomposition/_pca_0_23.py
>                  X_transformed = np.dot(X, self.components_.T)
This is a mistake. It should be like this:
```python
        if self.mean_ is not None:
            X = X - self.mean_
        X_transformed = np.dot(X, self.components_.T)
        if self.whiten:
            X_transformed /= np.sqrt(self.explained_variance_)
        return X_transformed
```
Now there is a chance that you will return None. This is bad.

2020-09-24 21:01 UTC, PetrovKP commented on generator/format.py
> +                    cppdefault = ' = {}'.format(cppdefaults[typ] if dflt == True else dflt)
```suggestion
                    cppdefault = ' = {}'.format(cppdefaults[typ] if dflt else dflt)
```

2020-09-24 21:01 UTC, PetrovKP commented on generator/gen_daal4py.py
> +                if tmp != None and not tmp.startswith('_') and not ignored(pns, tmp):
```suggestion
                if tmp is not None and not tmp.startswith('_') and not ignored(pns, tmp):
```

2020-09-25 10:50 UTC, PetrovKP approved these changes

2020-09-25 10:52 UTC, napetrov approved these changes

2020-09-25 10:54 UTC, merged